CREATE TABLE IF NOT EXISTS messages (
  id BIGINT AUTO_INCREMENT PRIMARY KEY ,
  listingId VARCHAR(36) NOT NULL,
  sellerId BIGINT NOT NULL,
  byerId BIGINT NOT NULL,
  message TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  sentByBuyer BOOLEAN NOT NULL
)