CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  url TEXT NOT NULL,
  message TEXT NOT NULL,
  CONSTRAINT fk_user_notifications FOREIGN KEY (user_id) REFERENCES users(id)
);