name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install maven -y
      - name: Build with Maven
        run: cd backend && mvn -B package -Dspring.profiles.active=test
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: backend-build
          path: backend/target/

  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run test:unit
      - run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: dist

  e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    env: 
      DATABASE_URL: jdbc:h2:mem:testdb;Mode=MySQL
      DATABASE_USER: h2
      DATABASE_PASSWORD=: h2
      SPRING_DATABASE_DRIVER: org.h2.Driver
    steps:
      - uses: actions/checkout@v4
      - name: Download Backend Artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-build
          path: backend/
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: frontend/
      - name: Install Frontend Dependencies
        run: cd frontend && npm ci
      - name: Start Backend
        run: |
          nohup java -jar backend/target/prosjektoppgave-0.0.1-SNAPSHOT.jar --spring.profiles.active=test > backend.log 2>&1 &
          sleep 10
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: frontend
          build: npm run build
          start: npm run preview